snowflakedb/pdo_snowflake

.travis.yml, scripts/run_travis.sh, tests/connect.phpt
For some reason, the environment variables are not set in the process of PHP test when running `make test`, so no connect information is propagated.
I tried to fix it by multiple ways, but none worked.
Now this change set is to replace the environment variable test connection parameters with ini file.
=> Replaced environment variables with the ini parameters

.gitignore, scripts/build_pdo_snowflake.sh, scripts/run_travis.sh
Forgot to ignore the test env file which includes the credential.
=> ignore test env ini. generate test env ini file in build and not at runtime

libsnowflakeclient/lib/snowflake_client.c, pdo_snowflake.c, php_pdo_snowflake_int.h, snowflake_driver.c, snowflake_stmt.c
Used 2 space tab, etc formats for PDO codes. Will sync up about Snowflake client tomorrow.
Removed null termination for data binding. NULL termination won't work for data including NULL...
=> reformat PDO codes. Use data length instead of strlen

snowflake_driver.c, snowflake_stmt.c
Valgrind found the memory and the cause was simply because it didn't call closing stmt.
=> fixed memory leak. Just forgot to call closing stmt

libsnowflakeclient/CMakeLists.txt, libsnowflakeclient/examples/CMakeLists.txt, libsnowflakeclient/examples/crud.c, libsnowflakeclient/examples/select1.c, libsnowflakeclient/examples/stmt_with_bad_connect.c, libsnowflakeclient/lib/snowflake_client.c, php_pdo_snowflake_int.h, snowflake_driver.c, snowflake_stmt.c, tests/connect.phpt
This change is to make SNOWFLAKE_STMT reusable.
The side effect is you no longer can bind columns *before* query/prepare, because they reset all status.
=> Fixed #35. Made SNOWFLAKE_STMT reusable for multiple queries

libsnowflakeclient/examples/connect.c, libsnowflakeclient/examples/crud.c, libsnowflakeclient/examples/example_setup.c, libsnowflakeclient/examples/ping_pong.c, libsnowflakeclient/examples/select1.c, libsnowflakeclient/examples/stmt_with_bad_connect.c, libsnowflakeclient/examples/transaction.c, libsnowflakeclient/examples/utils/example_setup.h, libsnowflakeclient/include/snowflake_client.h, libsnowflakeclient/lib/connection.c, libsnowflakeclient/lib/connection.h, libsnowflakeclient/lib/error.c, libsnowflakeclient/lib/error.h, libsnowflakeclient/lib/results.c, libsnowflakeclient/lib/results.h, libsnowflakeclient/lib/snowflake_client.c, php_pdo_snowflake_int.h, snowflake_driver.c, snowflake_stmt.c
Refactored typedefs to use SF_ instead of SNOWFLAKE_ consistently throughout the whole library. Changed SF_NO_ERROR and SF_JSON_NO_ERROR to SF_ERROR_NONE and SF_JSON_ERROR_NONE respectively to make enum error naming more consistent. Change was made using IDE so all references were changed. Fixes #26
=> Consistent naming

libsnowflakeclient/examples/crud.c, libsnowflakeclient/include/snowflake_client.h, libsnowflakeclient/lib/results.h, libsnowflakeclient/lib/snowflake_client.c, snowflake_driver.c, snowflake_stmt.c, tests/crud.phpt
- Added `snowflake_desc` to get the column metadata from stmt
- Change the function name `snowflake_param_count` to `snowflake_num_params` to be consistent with other `snowflake_num_*` function names.
- Implemented PDO statement column metadata callback
=> Added snowflake_desc and tests for both C and PHP

libsnowflakeclient/examples/CMakeLists.txt, libsnowflakeclient/examples/crud.c, libsnowflakeclient/examples/large_result_set.c, libsnowflakeclient/examples/select1.c, libsnowflakeclient/examples/selectvar.c, libsnowflakeclient/examples/stmt_with_bad_connect.c, libsnowflakeclient/examples/transaction.c, libsnowflakeclient/include/snowflake_client.h, libsnowflakeclient/lib/snowflake_client.c, snowflake_stmt.c, tests/select1.phpt, tests/selectvar.phpt
- Changed SF_BIND_OUTPUT.type to SF_BIND_OUTPUT.c_type to be consistent with SF_BIND_INPUT. I believe SF_BIND_INPUT requires `type` member anyway to specify Snowflake data type
- Fixed VARIANT, ARRAY and OBJECT binding and fetching support in PHP. No data size is given from the server, so it assumes the max length when fetching data.
=> added VARIANT, ARRAY and OBJECT binding and fetching support in PHP

libsnowflakeclient/include/snowflake_client.h, libsnowflakeclient/lib/snowflake_client.c
Removed calls to cJSON_GetArraySize with a chunk_rowcount variable for each statement object that keeps track of the number of rows left in the chunk. When this reaches 0, we replace the chunk.
=> Fetch Performance Improvements, Part 1

libsnowflakeclient/include/snowflake_basic_types.h, libsnowflakeclient/lib/connection.c, libsnowflakeclient/lib/results.c, snowflake_driver.c, snowflake_stmt.c, tests/selectbool.phpt
Fixed the boolean support for PHP.
The original implementation was return "TRUE" or "FALSE" for True and False string representation.
However, both are taken as True in PHP.
Although we could add PHP special case now, I changed the behavior for PHP, because no other driver has been requested on the top of C API. We may add a flag when we need different behavior later.
=> updated bool support. "1" for true and "" for false

libsnowflakeclient/examples/CMakeLists.txt, libsnowflakeclient/examples/check_ctypes.c, libsnowflakeclient/examples/crud.c, libsnowflakeclient/include/snowflake_client.h, libsnowflakeclient/lib/results.c, libsnowflakeclient/lib/results.h, libsnowflakeclient/lib/snowflake_client.c, snowflake_stmt.c
I changed the description interface to be an array of structs instead of an array of struct pointers. This reduces the number of memory allocations we have to do from (n + 1) to just 1 (amount of memory doesn't change, just number of memory allocation calls). Added support for REAL data type from Snowflake and added a test case to ensure we determine the right c_type in the column descriptions.
=> Get desc function

libsnowflakeclient/examples/CMakeLists.txt, libsnowflakeclient/examples/selecttsltz.c, libsnowflakeclient/include/snowflake_client.h, libsnowflakeclient/lib/snowflake_client.c, snowflake_stmt.c, tests/selectltz.phpt, tests/selectntz.phpt
- Added TIMESTAMP_LTZ support for PHP. When binding, the timestamp string must include the timezone offset, e.g., `1969-11-21 08:19:34.123000000 -05:00`
- Update `timezone` based on the response from the server.
- Added `static` to the existing functions, which are visible only in the file.
NOTE: C API uses the Snowflake session parameter `TIMEZONE` for the local timestamp conversion. This way, the application doesn't need to set the environment variable `TZ` but the session parameter.
=> Added TIMEZONE_LTZ support

snowflake_stmt.c
This is one of the recommendations from the pentest that was performed on the PDO driver
=> Removed logging of query statement

config.m4, config.w32, scripts/build_pdo_snowflake.bat, scripts/build_pdo_snowflake.sh
To be able to build on Windows and OSX
Known issues:
Windows: Negative epoch (date before 1970-01-01)  could cause incorrect result on timestamp data retrieval on Windows.
Fix is made in libsnowflakeclient here: https://github.com/snowflakedb/libsnowflakeclient/pull/249
need to update libsnowflakeclient library when the fix is merged.
Linux: year with less then 2 digits is represented as 2 digits, not 4 digits. For an example the date 0001-12-01 will be represented as 01-12-01. On Windows and OSX it's represented as 0001-12-01. It's the behavior of strftime() and the result is acceptable. No plan to fix it.
=> Update scripts for windows and osx build

README.rst
Description
Update the installation instructions for the PHP PDO Driver
- Because the driver needs to be built, move the build instructions to the beginning of the file.
- Indicate that the driver supports Windows and macOS.
- Update the Linux instructions to indicate that they apply to macOS.
- Change the build and installation instructions to use numbered steps.
Note that this just updates the installation instructions.
I'll send a separate PR to update the usage instructions.
=> SNOW-181550 Update the installation instructions for the PHP PDO Driver

README.rst
SNOW-181550
Description
Document cmake as a macOS requirement. If cmake is not installed, scripts/build_pdo_snowflake.sh exits silently after running
`which cmake`.
When I tried this out on my macOS machine (which had clang installed but not cmake), the `scripts/build_pdo_snowflake.sh` exited without printing out any information.
Adding `-x` to the line with `set -o pipefail` produced this output:
```
% ./scripts/build_pdo_snowflake.sh 
++++ dirname /<path>/pdo_snowflake/scripts/_init.sh
+++ cd /<path>/pdo_snowflake/scripts
+++ pwd
++ DIR=/<path>/pdo_snowflake/scripts
+++ tr '[:upper:]' '[:lower:]'
++++ uname
+++ echo Darwin
++ PLATFORM=darwin
+++ which cmake3
++ [[ -n '' ]]
+++ which cmake
++ CMAKE=
%
```
=> SNOW-181550 Document cmake as a macOS requirement

scripts/build_pdo_snowflake.sh
When build the driver with pre-installed PHP (not installed from source code), get error of "undefined symbol: uuid_unparse_lower)" when loading the driver from PHP.
Link with uuid library on Linux to fix this issue.
=> Fix uuid symbol not found issue on Linux

.github/workflows/BuildAndTest.yml
This will add a button for build-test workflow to run it manually . This will be useful for Releng team to run PHP tests on master or any other branch as part of pre-release of server release is done to ensure it does not break PHP connector
=> SNOW-208979 Add option to trigger Github Action Build/Test manually

README.rst
Minor update for the Windows build instructions.
=> SNOW-550117 Mheavin snow 550117 php win update

snowflake_driver.c, tests/connect.phpt
Simba ticket 00388800.
When creating connection with options (the last argument) like:
$pdoConnection = new PDO($dsn, $user, $password, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
auto commit is turned off which caused queries were silently rolled back later.
The root cause was a simple copy mistake. It make sense to turn over PDO_SNOWFLAKE_ATTR_SSL_VERIFY_CERTIFICATE_REVOCATION_STATUS because "verify=true" means "disable_verify = false" but no need to do that for auto commit.
=> bug fix: autocommit is turned over when creating connection with options

tests/callstmttype.phpt
Simba ticket 00383533
Add test case for new statement type for procedure call.
The server is adding a new statement type for procedure call in the query response send to client, the test case is to confirm if the driver works correctly with that.
The "alter session" query to enable the new statement type could fail if the server doesn't have the new behavior, so ignore that error to make the test case pass on server with old behavior, while the new behavior could be tested when it's rolled out on server side.
=> add test case for call statement type

tests/connect_negative.phpt
simba ticket 00404349
Key pair authentication doesn't work.
The bug is fixed on libsnowflakeclient side https://github.com/snowflakedb/libsnowflakeclient/pull/480
This PR just make the test case more specific to ensure the key pair auth parameters are passed to libsnowflakeclient correctly.
=> change test case to cover key pair auth with bug fix

.gitignore, composer.json, composer.lock
Request: https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/87
Snyk requirements for PHP: https://docs.snyk.io/scan-application-code/snyk-open-source/language-and-package-manager-support/snyk-for-php
Files changed:
- composer.json: This file describes the dependencies of the project and other metadata.
- composer.lock: This file is generated from composer.json and locks the project to specific versions of all packages.
- .gitignore: added the vendor folder as we don't want to add all of the third-party code to the repo repository. This is recommended by the composer docs.
Composer docs: https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies
Snyk only supports Composer for PHP which requires the composer.json and composer.lock files to be present in …
=> [#87] Add composer.json and composer.lock files for snyk test

scripts/_init.sh
sdk issue 477
output error message when cmake not installed.
=> error message when cmake not installed

snowflake_driver.c, tests/getattribute.phpt
sdk issue 585
Add support for ATTR_CLIENT_VERSION to allow getting driver version through API.
Will remove the exact version number from test case to avoid test case update for each release. Test in once though to ensure it's working.
Now the application can use PDO::getAttribute(PDO::ATTR_CLIENT_VERSION) https://www.php.net/manual/en/pdo.getattribute.php to retrieve the driver version.
=> add support for ATTR_CLINET_VERSION

.github/workflows/build_test.yml
Sometime we got build issue on Windows because PHP-8.4-dev was used instead of the PHP version we specified in test script.
Sounds like an issue with shivammathur/setup-php@v2 we used for setup PHP. Specify minor version could around this issue.
Also PHP 7.4 can't be built on github as it can't build with VS2019 and no previous VS versions available on github runners. Remove it from Windows build while still keep it on Linux/Mac. We should consider to remove 7.4 from support list though as it's end of life since 2022 Nov.
=> fix build issue on github Windows

pdo_snowflake.c, php_pdo_snowflake_int.h, snowflake_driver.c, snowflake_stmt.c, tests/getattribute.phpt
sdk issue124
In PDO the query execution is basically on connection level (.e.g using PDO::query https://www.php.net/manual/en/pdo.query.php) and the statement class is for one query returned from PDO::query(). https://www.php.net/manual/en/class.pdostatement.php
So the query id has to be saved on connection level. Especially for the failure case the PDO::query() return false and no statement instance available.
Add driver specific attribute SNOWFLAKE_ATTR_QUERY_ID can be used for PDO::getAttribute() and PDOStatement::getAttribute()
sample code:
```
$dbh = new PDO("snowflake:account=<account_name>", "<user>", "<password>");
$sth = $dbh->query("select 1");
$qid = $dbh->getAttribute(PDO::SNOWFLAKE_ATTR_QUERY_ID);
$sqid = $sth->getAttribute(PDO::SNOWFLAKE_ATTR_QUERY_ID);
```
both qid and sqid …
=> SNOW-726743: [HTAP] LAST QUERY ID - Driver API for PHP/PDO

.github/workflows/build_test.yml
Sync the MacOS clock before running the tests.
=> SNOW-982481: Sync MacOS time

.github/workflows/build_test.yml, README.rst, composer.json, composer.lock
Teamwork issue 928.
Would be a BCR as we drop support for PHP 8.0.
=> SNOW-1333636: drop PHP 8.0 and add 8.3 support

README.rst
This is a document-only change.
Apparently the version of `php-sdk-binary-tools/phpsdk-starter.bat` what we use bails out with `<token> was unexpected at this time.` where `<token>`is the first string following the first space in the path to the script.
E.g. running the script from `C:\temp\directory **name** with spaces\pdo_snowflake\scripts` will yield '`**name**` was unexpected at this time'
Per issues found in the source repo on what we rely, this is known and indeed not supported.
So documenting it.
=> Add instructions in README to not to use a space-containing dir on Windows

README.rst, pdo_snowflake.c, php_pdo_snowflake_int.h
teamwork issue 521
Since Easy logging is set through configuration file where the location of Easy logging file can be expected in various locations, this means manually testing of the feature is required. Therefore, the following tests cases were manually confirmed:
Test cases:
- verify search order of easy-logging file:
- set pdo_snowflake.clientconfigfile in php.ini
- set sf_client_config_file through environment variable 
- set sf_client_config.json in php folder
- set sf_client_config.json in User's home directory
- combination of settings used in php.ini:
- when both log dir, log path, and easy logging config file are not present, default logging will be used
- when both log dir and level are not set while easy logging config file is present, easy logging will be used
- when no log …
=> SNOW-856234 easy logging
