snowflakedb/pdo_snowflake

.gitignore
.travis.yml
pdo_snowflake.c
php_pdo_snowflake_int.h

Use PHP base image on travis and run build and tests on PHP 5.6 and 7.1

Use php base

---

.gitignore

ignoring logs and cmake build directory.

ignore logs and build directory

---

config.m4
libsnowflakeclient/examples/connect.c
libsnowflakeclient/examples/example_setup.c
libsnowflakeclient/examples/select1.c
pdo_snowflake.c
php_pdo_snowflake_int.h
snowflake_driver.c
snowflake_stmt.c
tests/select1.phpt

Added select1.phpt test case.
Updated PDO code in order to pass the test. It is not complete but works for now.
I'll revisit them as we add more tests.

added select1 test with PDO update

---

pdo_snowflake.c
php_pdo_snowflake.h
php_pdo_snowflake_int.h
snowflake_driver.c
snowflake_stmt.c
tests/select1.phpt

Added more tests to select1.phpt

Fixed memory leak

---

libsnowflakeclient/CMakeLists.txt
libsnowflakeclient/examples/crud.c
libsnowflakeclient/examples/transaction.c
libsnowflakeclient/include/snowflake_client.h
libsnowflakeclient/lib/results.c
libsnowflakeclient/lib/snowflake_client.c

Fixed #35 and Updated CRUD example.

Add crud test

---

libsnowflakeclient/include/snowflake_client.h
libsnowflakeclient/lib/snowflake_client.c

Recreated a new branch to minimize the merge conflict.

Added stmt attr methods. No attr is set yet

---

libsnowflakeclient/include/snowflake_client.h
libsnowflakeclient/lib/results.c
libsnowflakeclient/lib/results.h
libsnowflakeclient/lib/snowflake_client.c
php_pdo_snowflake_int.h
snowflake_driver.c
snowflake_stmt.c
tests/crud.phpt

Added CRUD php test case. Binding parameters support with the data length.
Fixed #27.

Add crud phpt

---

libsnowflakeclient/examples/crud.c
libsnowflakeclient/examples/select1.c
libsnowflakeclient/include/snowflake_client.h
libsnowflakeclient/lib/results.c
libsnowflakeclient/lib/snowflake_client.c
snowflake_stmt.c
tests/crud.phpt

Added is_dml function to detect DML and return the affected rows.

Implemented affected rows and test cases

---

snowflake_driver.c
snowflake_stmt.c

This change is just reformatted if else and label locations for PDO layer.
No change in Snowflake Connector yet to avoid merge conflict at the moment.

Reformated if else and label

---

libsnowflakeclient/include/snowflake_client.h
libsnowflakeclient/lib/connection.c
libsnowflakeclient/lib/error.c
libsnowflakeclient/lib/error.h
libsnowflakeclient/lib/snowflake_client.c
snowflake_driver.c
tests/error.phpt

This change propagates Snowflake Connector error to PHP PDO errors.

General error handling and test

---

libsnowflakeclient/examples/crud.c
libsnowflakeclient/examples/ping_pong.c
libsnowflakeclient/examples/select1.c
libsnowflakeclient/examples/stmt_with_bad_connect.c
libsnowflakeclient/examples/transaction.c
libsnowflakeclient/include/snowflake_client.h
libsnowflakeclient/lib/snowflake_client.c
snowflake_driver.c

Merged snowflake_close into snowflake_term

---

libsnowflakeclient/examples/crud.c
libsnowflakeclient/examples/error_handling.c
libsnowflakeclient/examples/ping_pong.c
libsnowflakeclient/examples/select1.c
libsnowflakeclient/examples/stmt_with_bad_connect.c
libsnowflakeclient/examples/transaction.c
libsnowflakeclient/include/snowflake_client.h
libsnowflakeclient/lib/snowflake_client.c
snowflake_driver.c
snowflake_stmt.c

Replace snowflake stmt close

---

tests/connect.phpt
tests/crud.phpt
tests/error.phpt
tests/select1.phpt

https://qa.php.net/write-test.php

Updated PHP test cases to make runnable standalone PHP application

---

libsnowflakeclient/include/snowflake_client.h
libsnowflakeclient/lib/snowflake_client.c
pdo_snowflake.c
php_pdo_snowflake_int.h
snowflake_driver.c
tests/connect.phpt
tests/crud.phpt
tests/error.phpt
tests/select1.phpt

- Moved CA cert file parameter from PHP connection object to PHP ini

Moved CA cert file parameter from PHP connection object to PHP ini

---

README.rst
tests/common.php
tests/connect.phpt
tests/crud.phpt
tests/error.phpt
tests/select1.phpt

Figured out how to include PHP file in tests.
Connection parameters should be set consistently.

Consolidate PHP tests using a common.php

---

.gitignore
libsnowflakeclient/examples/example_setup.c
libsnowflakeclient/examples/transaction.c
libsnowflakeclient/examples/utils/example_setup.h
libsnowflakeclient/lib/connection.c
libsnowflakeclient/lib/connection.h
libsnowflakeclient/lib/snowflake_client.c
snowflake_driver.c
tests/binding.phpt
tests/crud.phpt
tests/transaction.phpt

- Implemented begin, commit and rollback for both C and PHP.
- Autocommit=false mode is not tested yet.

added transaction support

---

libsnowflakeclient/lib/snowflake_client.c
libsnowflakeclient/lib/snowflake_client_int.h

Delete session in snowflake_term

---

libsnowflakeclient/examples/CMakeLists.txt
libsnowflakeclient/examples/crud.c
libsnowflakeclient/examples/selectnum.c
snowflake_stmt.c
tests/selectnum.phpt
tests/selectvar.phpt

- Allocation 256 bytes for REAL data result. In theory, we cannot have the maximum number of digits for IEEE 754, but 256 bytes should be reasonable amount of memory. Will revisit this later.

Added REAL data type support

---

libsnowflakeclient/include/snowflake_logger.h
libsnowflakeclient/lib/snowflake_client.c

My bad. The previous merge broke main.

fixed logger enum error

---

libsnowflakeclient/CMakeLists.txt
libsnowflakeclient/examples/crud.c
libsnowflakeclient/lib/chunk_downloader.c
libsnowflakeclient/lib/chunk_downloader.h
libsnowflakeclient/lib/connection.c
libsnowflakeclient/lib/connection.h
libsnowflakeclient/lib/snowflake_client.c
libsnowflakeclient/lib/snowflake_memory.c
snowflake_stmt.c

Make warnings into error

---

libsnowflakeclient/lib/chunk_downloader.c
libsnowflakeclient/lib/connection.c

Fixed warning level bugs pointed out by Markus.

---

libsnowflakeclient/CMakeLists.txt
libsnowflakeclient/examples/large_result_set.c
tests/largeresultset.phpt

- Added a large result set test case for PHP
- Enabled profiler option by default
- Updated the large result set test example for C

added large result set tests in PHP

---

libsnowflakeclient/examples/CMakeLists.txt
libsnowflakeclient/examples/selectbin.c
libsnowflakeclient/include/snowflake_client.h
libsnowflakeclient/lib/results.c
snowflake_stmt.c
tests/selectbin.phpt
tests/selectvar.phpt

- Added BINARY support for PHP
- The returned value is still in hex string.

Added BINARY support for PHP

---

libsnowflakeclient/lib/snowflake_client.c
snowflake_stmt.c
tests/selectdate.phpt

- Added DATE type support for PHP. Basically PHP has to bind datetime data as string.

Add more php datatype

---

snowflake_stmt.c
tests/binding.phpt

Fixed bindColumn support

---

libsnowflakeclient/examples/CMakeLists.txt
libsnowflakeclient/examples/selectnull.c
libsnowflakeclient/lib/results.c
libsnowflakeclient/lib/snowflake_client.c
libsnowflakeclient/lib/snowflake_logger.c
snowflake_stmt.c
tests/selectnull.phpt

- Fixed null insert and select
- Flush log message on every output

Added NULL support

---

libsnowflakeclient/include/snowflake_client.h
libsnowflakeclient/lib/connection.c
libsnowflakeclient/lib/snowflake_client.c
php_pdo_snowflake_int.h
snowflake_driver.c

- Fixed application name and version
- Use them for PHP PDO driver
- Fixed timezone memory

Fixed application name, version and OS info

---

libsnowflakeclient/examples/CMakeLists.txt
libsnowflakeclient/examples/selecttsntz.c
libsnowflakeclient/lib/snowflake_client.c
snowflake_stmt.c
tests/selectntz.phpt

- Added TIMESTAMP_NTZ support for PHP.

added TIMESTAMP_NTZ support for PHP

---

libsnowflakeclient/examples/CMakeLists.txt
libsnowflakeclient/examples/selecttstz.c
libsnowflakeclient/lib/snowflake_client.c
tests/selectltz.phpt
tests/selecttz.phpt

- Added TIMESTAMP_TZ support for PHP

Add timestamp tz support

---

libsnowflakeclient/examples/CMakeLists.txt
libsnowflakeclient/examples/selecttime.c
libsnowflakeclient/lib/snowflake_client.c
tests/selecttime.phpt

- Added TIME data type support for PHP

Added TIME support for PHP

---

config.m4
libsnowflakeclient/examples/connect.c
libsnowflakeclient/examples/error_handling.c
libsnowflakeclient/examples/example_setup.c
libsnowflakeclient/examples/stmt_with_bad_connect.c
libsnowflakeclient/examples/timezone.c
libsnowflakeclient/include/snowflake_client.h
libsnowflakeclient/lib/snowflake_client.c
pdo_snowflake.c
php_pdo_snowflake.h
php_pdo_snowflake_int.h
snowflake_driver.c
snowflake_stmt.c

- Added -Werror to PDO build and fixed all warnings
- Added more SQLSTATE for CLI. Will work on more error handling

Added -Werror to PDO build and fixed all warnings

---

libsnowflakeclient/examples/check_ctypes.c
libsnowflakeclient/examples/crud.c
libsnowflakeclient/examples/large_result_set.c
libsnowflakeclient/examples/select1.c
libsnowflakeclient/examples/selectbin.c
libsnowflakeclient/examples/selectbool.c
libsnowflakeclient/examples/selectnull.c
libsnowflakeclient/examples/selectnum.c
libsnowflakeclient/examples/selecttime.c
libsnowflakeclient/examples/selecttsltz.c
libsnowflakeclient/examples/selecttsntz.c
libsnowflakeclient/examples/selecttstz.c
libsnowflakeclient/examples/selectvar.c
libsnowflakeclient/examples/stmt_with_bad_connect.c
libsnowflakeclient/examples/timezone.c
libsnowflakeclient/include/snowflake/client.h
libsnowflakeclient/lib/chunk_downloader.c
libsnowflakeclient/lib/client.c
libsnowflakeclient/lib/connection.c
libsnowflakeclient/lib/error.c
libsnowflakeclient/lib/error.h
snowflake_driver.c
snowflake_stmt.c

Fixed #113 and #114 
SF_STATUS
- 0 ... success
- >0 ... errors
- <0 ... special values
Changed EOL to EOF

Merged SF_ERROR_CODE into SF_STATUS

---

.gitignore
README.rst
libsnowflakeclient/CMakeLists.txt
libsnowflakeclient/examples/error_handling.c
libsnowflakeclient/scripts/build_libsnowflakeclient.sh
libsnowflakeclient/scripts/run_tests.sh
scripts/build_pdo_snowflake.sh
scripts/run_tests.sh
scripts/run_travis.sh

Added c tests to travis

---

scripts/create_schema.py
scripts/drop_schema.py
scripts/run_travis.sh

- Allow Travis tests in parallel by using the test specific schema
- Fold Travis Log for better view

Run tests in parallel using a test specific schema

---

docker/Dockerfile.ubuntu14
docker/Dockerfile.ubuntu16
docker/README.rst
docker/build.sh

- Added docker files for Ubuntu 14 and 16 for tests

Add docker files

---

libsnowflakeclient/examples/CMakeLists.txt
libsnowflakeclient/examples/bind_params.c
libsnowflakeclient/examples/bind_results.c
libsnowflakeclient/include/snowflake/client.h
libsnowflakeclient/lib/client.c

Bind Array functionality and unit tests

Bind array

---

.travis.yml
docker/Dockerfile.ubuntu14
docker/Dockerfile.ubuntu16
docker/Dockerfile.ubuntu18
docker/README.rst
docker/scripts/build.sh
docker/scripts/build_run_ubuntu.sh
scripts/run_docker_test.sh

This covers tests on:
- Ubuntu 14.04 PHP 7.0
- Ubuntu 14.04 PHP 7.1
- Ubuntu 16.04 PHP 7.1
- Ubuntu 18.04 PHP 7.2

Run tests on dockers

---

libsnowflakeclient/include/snowflake/logger.h

Just regular sync up. No bug fixe or improvement.

Update CAPI clients

---

README.rst
docker/README.rst
docker/scripts/build_run_ubuntu_with_proxy.sh
docker/test-proxy/Dockerfile.ubuntu14
docker/test-proxy/Dockerfile.ubuntu16
docker/test-proxy/Dockerfile.ubuntu18
docker/test-proxy/README.rst
docker/test-proxy/build.sh
docker/test-proxy/iptables.txt
docker/test-proxy/run.sh
scripts/build_pdo_snowflake.sh

Updated PHP PDO Driver README with instructions for adding proxy.

PHP PDO Driver README Update

---

README.rst

Updated to show current limitations and how to build/install on Windows.

Updated documentation

---

tests/common.php
tests/connect_negative.phpt

This was removed in libsnowflakeclient a while ago, but we did not remove this from the PDO Driver.

Removed missing database test

---

README.rst
scripts/build_pdo_snowflake.sh
scripts/run_tests.sh
scripts/run_travis.sh

PR-193 plus a small change to make tests on Travis work

Decouple env setup

---

README.rst

SNOW-181550
Description
Fix the installation section and make changes to the instructions on using the driver
- Replace the PHP build instructions with a pointer to the PHP docs, which includes additional information about
prerequisites (e.g. libxml2).
- Clean up some of the sections under using the driver.

SNOW-181550 Fix the installation section and make changes to the instructions for using the driver

---

README.rst

Description
Remove the limitations section. The limitations have been addressed.

SNOW-259162 Remove the limitations section

---

snowflake_driver.c

Fix for simbe ticket 00320573, error log was logged at debug level.

correct loglevel for error log

---

README.rst

Summary of changes:
* Add mention of PHP 7.4
* Mention that PHP 7.2 is deprecated
Testing: local HTML build to check presentation and clarity
N/A

SNOW-429543 Document support for PHP 7.4

---

.github/workflows/jira_comment.yml
.github/workflows/jira_issue.yml

Committed via https://github.com/asottile/all-repos

SNOW-499170 Bringing GH actions up-to-date with Python connector's

---

php_pdo_snowflake.h

Bump Up PHP version to 1.2.1 from 1.2.0

Bump Up PHP version to 1.2.1 from 1.2.0

---

README.rst

Added 8.1 to supported versions
Quick approval requested

SNOW-563024-php-version

---

php_pdo_snowflake.h

Bump Up PDO Client version to 1.2.3

---

README.rst

I added a subsection for Using Key Pair Authentication.

Mheavin snow 640361 php keypair

---

php_pdo_snowflake.h

SNOW-624701 Bump Up PHP PDO Version to 1.2.4

SNOW-624701 Bump Up PHP PDO Version to 1.2.4

---

snowflake_stmt.c
tests/binding.phpt
tests/selectnull.phpt

Take bug fix from https://github.com/snowflakedb/pdo_snowflake/pull/298, add test case as well.

SNOW-704522: PDO driver returns empty strings instead of NULL values when using PHP 8.1

---

.vscode/settings.json
README.rst

Update Windows build instructions
DOC-636

Mheavin doc 636 php windows install

---

README.rst

Added content I accidentally forgot to push before merging mheavin-doc-636-php-windows-install

DOC-638 Update uncommitted content

---

php_pdo_snowflake.h

Update php version for client release

SNOW-824450 Bump Version - Update php_pdo_snowflake.h

---

.github/workflows/build_test_linux_php8-1.yml
.github/workflows/scripts/test_driver.py
config.m4
scripts/build_pdo_snowflake.sh
snowflake_driver.c
snowflake_rbtree.c
tests/bind_named_parameters.phpt
tests/binding.phpt
tests/getattribute.phpt

sdk issue 115
generate code coverage report and add test cases.
The code coverage number is 85.6%.
https://github.com/snowflakedb/pdo_snowflake/actions/runs/5686751884/job/15414087240?pr=325

generate code coverage report and add test cases

---

.github/workflows/build_test.yml

sdk issue 546
No code change but only add test on 8.2 as all test passed.

Add support for PHP8.2

---

.github/workflows/build_test.yml
.github/workflows/scripts/test_driver.py
tests/getattribute.phpt

Issue 544: https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/544
Added steps to upload code coverage report to Codecov in Github action.
https://app.codecov.io/gh/snowflakedb/pdo_snowflake/tree/SNOW-870363-codecov-integration

SNOW-870363: Integrate code coverage with CodeCov

---

php_pdo_snowflake.h

Bump up php driver version to 2.0.0.

SNOW-921837 - Bump up php driver version to 2.0.0

---

README.rst

sdk issue 476
Update the documentation for the case that cloud needs to be specified in region or account.

SNOW-844459: update doc adding cloud in region

---

README.rst

This is undocumented and leads to issues/cases created. While the feature gets implemented, lets document the lack of it.

SNOW-986383 document no arm support yet in linux

---

tests/connect_negative.phpt
tests/lob.phpt

sdk issue 748
test with max lob size only as the major functionality is tested in libsnowflakeclient

SNOW-969715: add test case for max lob size

---

.github/workflows/semgrep.yml

Security Update: This PR creates/updates the Semgrep static analysis workflow. Local semgrep rules have been deleted. If your repo had a semgrep stage in the Jenkinsfile, we attempted to delete it. Please review changes and merge them as soon as possible.

SNOW-667402:Semgrep workflow update

---

snowflake_stmt.c

SNOW-1045516: fix crash issue with debug logging

---

.github/workflows/jira_issue.yml

Update area in JIRA integration

SNOW-1111018: Update area in JIRA integration

---

README.rst

Documenting proxy settings available since 1.2.5

SNOW-610076-document-proxy-settings

---

README.rst

SNOW-1229299 Update README.rst with configurable timeouts

SNOW-1229299 Update README.rst with configurable timeouts

---

SECURITY.md

Update of the security policy for reporting security issues in the repository

SNOW-1293828 security policy tab

---

tests/bind_named_parameters.phpt
tests/binding.phpt
tests/callstmttype.phpt
tests/connect.phpt
tests/connect_negative.phpt
tests/crud.phpt
tests/debugdump.phpt
tests/error.phpt
tests/fetching.phpt
tests/getattribute.phpt
tests/htap.phpt
tests/issue_152.phpt
tests/largeresultset.phpt
tests/lob.phpt
tests/ocsp.phpt
tests/proxy.phpt
tests/select1.phpt
tests/selectbin.phpt
tests/selectbool.phpt
tests/selectdate.phpt
tests/selectltz.phpt
tests/selectntz.phpt
tests/selectnull.phpt
tests/selectnum.phpt
tests/selecttime.phpt
tests/selecttz.phpt
tests/selectvar.phpt
tests/timezone.phpt
tests/transaction.phpt
tests/twentystring.phpt

teamwork issue 864
enable debug logging for all test cases to ensure no further issues with logging.

SNOW-1045516: enable debug logging for all test cases

---

README.rst
scripts/env.bat

SNOW-921965: document update and correction

---

pdo_snowflake.c

SNOW-1367439: change default loglevel to FATAL

---

README.rst

SNOW-1526511: update doc for host support in connection parameter

---

README.rst

SNOW-1105666: Add reference link for supported OS

---

snowflake_stmt.c
tests/memory_usage.phpt

teamwork issue 1209
It might not be the root cause of the OOM issue but found during the investigation and should be fixed.

SNOW-1887475: fix for memory leak
